**Braod Casting in NumPy**

In [ ]:
#board casting in numpy
import numpy as np
a = np.array([1, 2, 3])
print(a + 5)

[6 7 8]


**Basic Operation in NumPy**

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  #addition
print(a - b)  #subtraction
print(a * b)  #multiplication
print(a / b)  #division

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


**Shape Manipulation**

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.reshape(3, 2))  #rehspe
print(a.flatten())  #Flattening
print(a.T)  #Transposing

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


**Array Manipulation in NumPy**

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)  #reshape
print(b)
print(b[0])   #indexing

[[1 2 3]
 [4 5 6]]
[1 2 3]


**Structured Array**

In [ ]:
import numpy as np
data =  np.array([
                 (1, "shaik", 85.5),
                  (2, "Abdul", 90.0),
                 (3, "Famim", 78.0)
                 ], dtype = [('id', 'i4'), ('name', 'U10'), ('marks', 'f4')])
print(data)


[(1, 'shaik', 85.5) (2, 'Abdul', 90. ) (3, 'Famim', 78. )]
